name: CI PicPay KMP
on:
  push:
    branches: [ "main", "main" ]
  pull_request:
    branches: [ "main", "main" ]

jobs:
  # ü§ñ  ANDROID
  android-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Tests & Build (Android)
        run: ./gradlew assembleDebug testDebugUnitTest

  # üçé  IOS
  ios-check:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Tests (IOS)
        run: ./gradlew iosSimulatorArm64Test

  # üñ•Ô∏è Windows
  test-windows:
   name: Run Tests on Windows
   runs-on: windows-latest

   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Run Desktop Tests
      run: ./gradlew desktopTest --info