name: CI PicPay KMP
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  # ü§ñ  ANDROID
  android-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Rodar Testes e Build Android
        run: ./gradlew assembleDebug testDebugUnitTest

  # üçé  IOS
  ios-check:
    runs-on: macos-latest
    needs: android-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build iOS Framework
        run: ./gradlew linkDebugFrameworkIosArm64